GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU4NTE0MjgxM30.hG9mW3A0TF8lZuSclhQQAMW0Jgc8cw9HkBeIj6nb5dE
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}