POST http://localhost:4000/register
Content-Type: application/json

{
    "email":"test@test2.com",
    "password":"q1w2e3"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"q1w2e3"
}

###

POST http://localhost:4000/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjAsImlhdCI6MTU4NTE0ODg3MCwiZXhwIjoxNTg1MTQ5NzcwfQ.4uYqoxJeoZE7jpy9X713MaUdRLdENfjvE__wVydmWc4